// AUTO-GENERATED by theme-core sync — do not edit.
// To take ownership of this file, add an eject comment (see theme-core docs).
import { dev } from "$app/environment";
import { error } from "@sveltejs/kit";
import themeConfig from "../../../../../theme.config.js";
import { setThemeConfig } from "$pano/registry/index.js";

setThemeConfig(themeConfig);

export const GET = async (event) => {
  const m = dev ? await import("$pano/routes/catalogue/views-json.js") : null;
  if (!m) throw error(404, "Not found");
  return m.GET(event);
};
