<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import Error from "$pano/lib/pages/ErrorPage.svelte";
</script>

<Error />
