<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import RootLayout from "$pano/routes/RootLayout.svelte";

  export let data;
</script>

<RootLayout {data}><slot /></RootLayout>
