// AUTO-GENERATED by theme-core sync — do not edit.
// To take ownership of this file, add an eject comment (see theme-core docs).
import themeConfig from "../../theme.config.js";
import { setThemeConfig } from "$pano/registry/index.js";

// Module side effect: the registry is populated on server and client before
// any load function runs.
setThemeConfig(themeConfig);

export { load } from "$pano/routes/root-layout-load.js";
