// AUTO-GENERATED by theme-core sync — do not edit.
// To take ownership of this file, add an eject comment (see theme-core docs).
export { loadServer as load } from "$pano/lib/layouts/AppLayout.svelte";
