<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ActivateEmailPage from "$pano/lib/pages/ActivateEmailPage.svelte";

  export let data;
</script>

<ActivateEmailPage {data}/>
