<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import Home from "$pano/lib/pages/HomePage.svelte";

  export let data;
</script>

<Home {data}/>
