<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import AuthLayout from "$pano/lib/layouts/AuthLayout.svelte";
</script>

<AuthLayout><slot /></AuthLayout>
