<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import LoginPage from "$pano/lib/pages/LoginPage.svelte";

  export let data;
</script>

<LoginPage {data}/>
