<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ProfileLayout from "$pano/lib/layouts/ProfileLayout.svelte";
</script>

<ProfileLayout><slot /></ProfileLayout>
