<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ProfilePage from "$pano/lib/pages/profile/ProfilePage.svelte";

  export let data;
</script>

<ProfilePage {data}/>
