<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import RulesPage from "$pano/lib/pages/RulesPage.svelte";

  export let data;
</script>

<RulesPage {data}/>
