<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import CreateTicketPage from "$pano/lib/pages/ticket/CreateTicketPage.svelte";

  export let data;
</script>

<CreateTicketPage {data}/>
