<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import PostDetailPage from "$pano/lib/pages/PostDetailPage.svelte";

  export let data;
</script>

<PostDetailPage {data}/>
