// AUTO-GENERATED by theme-core sync — do not edit.
// To take ownership of this file, add an eject comment (see theme-core docs).
import { dev } from "$app/environment";
import { error } from "@sveltejs/kit";

export const ssr = !dev;

export const load = async (event) => {
  const m = dev ? await import("$pano/routes/catalogue/list.js") : null;
  if (!m) throw error(404, "Not found");
  return m.load(event);
};
