<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  export let data;
</script>

<svelte:component this={data.component} {data} />
