<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import RenewPasswordPage from "$pano/lib/pages/RenewPasswordPage.svelte";

  export let data;
</script>

<RenewPasswordPage {data}/>
