<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ResetPasswordPage from "$pano/lib/pages/ResetPasswordPage.svelte";

  export let data;
</script>

<ResetPasswordPage />
