<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import RegisterPage from "$pano/lib/pages/RegisterPage.svelte";

  export let data;
</script>

<RegisterPage {data}/>
