<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import PlayerDetailPage from "$pano/lib/pages/PlayerDetailPage.svelte";

  export let data;
</script>

<PlayerDetailPage {data}/>
