// Typedefs of the public controllers of pano-plugin-market (doc 02 section 2: `types.js` is the typedef module). No code.
// State shapes list EVERY public key: a controller's initial state holds all of them (doc 02 section 1).

/** @typedef {import('@panomc/plugin-kit/controller').ControllerHost} ControllerHost */

/** @typedef {{ ok: true, [key: string]: any } | { ok: false, code: string, [key: string]: any }} ApiResult */

/**
 * `market/session`, eager: the signed-in user, fed by `host.onSession`.
 * @typedef {{ user: object | null, isLoggedIn: boolean, csrfToken: string | null }} SessionState
 */

/** `market/settings`: the `settings` object of GET /store (null until a page or `ensure` stored it). @typedef {{ settings: object | null }} SettingsState */

/** `market/clock`: epoch milliseconds, 0 on the server, ticking every second while subscribed. @typedef {{ now: number }} ClockState */

/** `market/currency`: the preferred display currency (ISO code or null). @typedef {{ preferred: string | null }} CurrencyState */

/**
 * `market/cart`, eager: today's cart store state plus the pending replace question.
 * @typedef {{ mode: 'NONE'|'GUEST'|'SERVER', status: 'IDLE'|'LOADING'|'SYNCING'|'ERROR', lines: object[], quote: object | null,
 *   quoteStale: boolean, count: number, error: string | null, codes: object | null, reduced: string[],
 *   replaceRequest: { line: object, product: object } | null }} CartState
 */

/** `market/checkoutDraft`, eager: the draft of the checkout form (see `defaultDraft()` in lib/checkoutDraftModel.js). @typedef {ReturnType<typeof import('../lib/checkoutDraftModel.js').defaultDraft>} CheckoutDraftState */

/** `market/profile`, eager: the `me/summary` of the signed-in user (null: unknown, signed out or failed). @typedef {{ summary: object | null }} ProfileState */

/**
 * Params of the four page loaders (`market/store`, `product`, `order`, `checkout`): `event.params` of the route, plus
 * `url` (the request URL as a string or URL; the controller reads the query and the origin from it). Without `url` the
 * query is empty and the origin is `host.baseUrl`.
 * @typedef {{ url?: string | URL, slug?: string, id?: string }} PageLoadParams
 */

/**
 * What a page loader resolves: the view's `load` result of today (`{ data, ... }`), plus `redirect` ({ status, location })
 * where the old load threw a redirect, and `notFound: true` where it threw a 404. The view turns those into its throw.
 * @typedef {{ data?: object, redirect?: { status: number, location: string }, notFound?: boolean, [key: string]: any }} PageLoadResult
 */

export {};

// ---- generated by @panomc/plugin-kit, do not edit below this line ----

/**
 * What a theme, a web component or plain JS holds. `name` is "market/cart" (namespace + "/" + spec.name).
 * `get()` is a snapshot, replaced on change and never mutated.
 * @template S, A
 * @typedef {Object} Controller
 * @property {string} name
 * @property {number} version
 * @property {() => S} get
 * @property {(run:(s:S)=>void) => (() => void)} subscribe
 * @property {A} actions
 * @property {() => void} destroy
 */

/**
 * @typedef {Object} ControllerHost
 * @property {string} baseUrl
 * @property {boolean} browser
 * @property {(r:{method?:string, path:string, query?:object, body?:any, headers?:object, blob?:boolean}) => Promise<any>} request
 *   Parsed body in doc 04's shape (non-2xx = { error: { code, ... } }). `path` is what follows "/api/v1".
 *   A network failure resolves { error: { code: 'NETWORK_ERROR' } }; request never rejects.
 * @property {() => {user:(object|null), csrfToken:(string|null)}} session
 * @property {() => (string|undefined)} locale
 * @property {(fn:(s:any)=>void) => (() => void)} onSession   first bind, login, logout; a no-op on the server
 * @property {(key:string, values?:object) => string} t        full key: "plugins.pano-plugin-market.x"
 * @property {(key:string, o?:{variant?:'success'|'danger'|'warning', values?:object}) => void} toast
 * @property {(kind:'local'|'session') => (Storage|null)} storage
 * @property {() => number} now
 * @property {(url:string, o?:{replace?:boolean}) => void} navigate
 * @property {(name:string) => boolean} feature
 * @property {(returnTo?:string) => string} loginUrl
 * @property {(returnTo?:string) => string} registerUrl
 */

/**
 * What `host.request` resolves, and what an action returns when it can fail: the parsed body, or the error envelope.
 * @template [T=object]
 * @typedef {T | { error: { code: string, message?: string, details?: object, fields?: Record<string, string> } }} ApiResult
 */

/**
 * State of market/api, generated from the keys of its initial state (declare ApiState in types.js to type it).
 * @typedef {{}} ApiState
 */

/**
 * Actions of market/api, generated from its action names (declare ApiActions in types.js to type them).
 * @typedef {{ call: (...args: any[]) => any, apiGet: (...args: any[]) => any, post: (...args: any[]) => any, put: (...args: any[]) => any, del: (...args: any[]) => any }} ApiActions
 */

/**
 * Actions of market/cart, generated from its action names (declare CartActions in types.js to type them).
 * @typedef {{ init: (...args: any[]) => any, autoInit: (...args: any[]) => any, add: (...args: any[]) => any, update: (...args: any[]) => any, setQuantity: (...args: any[]) => any, remove: (...args: any[]) => any, clear: (...args: any[]) => any, putCart: (...args: any[]) => any, setCurrency: (...args: any[]) => any, afterCheckout: (...args: any[]) => any, requestQuote: (...args: any[]) => any, watchQuotes: (...args: any[]) => any, retry: (...args: any[]) => any, clampToQuote: (...args: any[]) => any, confirmReplace: (...args: any[]) => any, cancelReplace: (...args: any[]) => any, reset: (...args: any[]) => any }} CartActions
 */

/**
 * State of market/checkout, generated from the keys of its initial state (declare CheckoutState in types.js to type it).
 * @typedef {{}} CheckoutState
 */

/**
 * Actions of market/checkout, generated from its action names (declare CheckoutActions in types.js to type them).
 * @typedef {{}} CheckoutActions
 */

/**
 * Actions of market/checkoutDraft, generated from its action names (declare CheckoutDraftActions in types.js to type them).
 * @typedef {{ get: (...args: any[]) => any, restore: (...args: any[]) => any, patch: (...args: any[]) => any, set: (...args: any[]) => any, flush: (...args: any[]) => any, clear: (...args: any[]) => any, detach: (...args: any[]) => any, sessionChanged: (...args: any[]) => any }} CheckoutDraftActions
 */

/**
 * Actions of market/clock, generated from its action names (declare ClockActions in types.js to type them).
 * @typedef {{}} ClockActions
 */

/**
 * Actions of market/currency, generated from its action names (declare CurrencyActions in types.js to type them).
 * @typedef {{ init: (...args: any[]) => any, setPreferred: (...args: any[]) => any, effective: (...args: any[]) => any, adoptUrl: (...args: any[]) => any, needsRefetch: (...args: any[]) => any, isMulti: (...args: any[]) => any }} CurrencyActions
 */

/**
 * State of market/format, generated from the keys of its initial state (declare FormatState in types.js to type it).
 * @typedef {{}} FormatState
 */

/**
 * Actions of market/format, generated from its action names (declare FormatActions in types.js to type them).
 * @typedef {{ formatPrice: (...args: any[]) => any, formatMoney: (...args: any[]) => any, formatCredits: (...args: any[]) => any, formatDate: (...args: any[]) => any, formatDateTime: (...args: any[]) => any, formatPeriod: (...args: any[]) => any, countryName: (...args: any[]) => any }} FormatActions
 */

/**
 * State of market/host, generated from the keys of its initial state (declare HostState in types.js to type it).
 * @typedef {{}} HostState
 */

/**
 * Actions of market/host, generated from its action names (declare HostActions in types.js to type them).
 * @typedef {{ has: (...args: any[]) => any, loginUrl: (...args: any[]) => any, registerUrl: (...args: any[]) => any }} HostActions
 */

/**
 * State of market/order, generated from the keys of its initial state (declare OrderState in types.js to type it).
 * @typedef {{}} OrderState
 */

/**
 * Actions of market/order, generated from its action names (declare OrderActions in types.js to type them).
 * @typedef {{}} OrderActions
 */

/**
 * State of market/product, generated from the keys of its initial state (declare ProductState in types.js to type it).
 * @typedef {{}} ProductState
 */

/**
 * Actions of market/product, generated from its action names (declare ProductActions in types.js to type them).
 * @typedef {{}} ProductActions
 */

/**
 * Actions of market/profile, generated from its action names (declare ProfileActions in types.js to type them).
 * @typedef {{ refresh: (...args: any[]) => any, reset: (...args: any[]) => any, setLoader: (...args: any[]) => any }} ProfileActions
 */

/**
 * Actions of market/session, generated from its action names (declare SessionActions in types.js to type them).
 * @typedef {{ sync: (...args: any[]) => any, onChange: (...args: any[]) => any }} SessionActions
 */

/**
 * Actions of market/settings, generated from its action names (declare SettingsActions in types.js to type them).
 * @typedef {{ set: (...args: any[]) => any, ensure: (...args: any[]) => any }} SettingsActions
 */

/**
 * State of market/store, generated from the keys of its initial state (declare StoreState in types.js to type it).
 * @typedef {{}} StoreState
 */

/**
 * Actions of market/store, generated from its action names (declare StoreActions in types.js to type them).
 * @typedef {{}} StoreActions
 */

/**
 * State of market/widgets, generated from the keys of its initial state (declare WidgetsState in types.js to type it).
 * @typedef {{}} WidgetsState
 */

/**
 * Actions of market/widgets, generated from its action names (declare WidgetsActions in types.js to type them).
 * @typedef {{}} WidgetsActions
 */

/**
 * Every public controller of market, by full name.
 * @typedef {{ 'market/api': Controller<ApiState, ApiActions>, 'market/cart': Controller<CartState, CartActions>, 'market/checkout': Controller<CheckoutState, CheckoutActions>, 'market/checkoutDraft': Controller<CheckoutDraftState, CheckoutDraftActions>, 'market/clock': Controller<ClockState, ClockActions>, 'market/currency': Controller<CurrencyState, CurrencyActions>, 'market/format': Controller<FormatState, FormatActions>, 'market/host': Controller<HostState, HostActions>, 'market/order': Controller<OrderState, OrderActions>, 'market/product': Controller<ProductState, ProductActions>, 'market/profile': Controller<ProfileState, ProfileActions>, 'market/session': Controller<SessionState, SessionActions>, 'market/settings': Controller<SettingsState, SettingsActions>, 'market/store': Controller<StoreState, StoreActions>, 'market/widgets': Controller<WidgetsState, WidgetsActions> }} Controllers
 */
