<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import TicketsLayout from "$pano/lib/layouts/TicketsLayout.svelte";
</script>

<TicketsLayout><slot /></TicketsLayout>
