<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import TicketsPage from "$pano/lib/pages/profile/TicketsPage.svelte";

  export let data;
</script>

<TicketsPage {data}/>
