<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import TicketDetailPage from "$pano/lib/pages/ticket/TicketDetailPage.svelte";

  export let data;
</script>

<TicketDetailPage {data}/>
