<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import PreviewPostPage from "$pano/lib/pages/PreviewPostPage.svelte";

  export let data;
</script>

<PreviewPostPage post="{data.post}"/>
