<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ConfirmNewEmailPage from "$pano/lib/pages/ConfirmNewEmailPage.svelte";

  export let data;
</script>

<ConfirmNewEmailPage {data}/>
