<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ThemeSettingsLayout from "$pano/lib/layouts/ThemeSettingsLayout.svelte";
</script>

<ThemeSettingsLayout><slot /></ThemeSettingsLayout>
