<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import ThemeSettingsPage from "$pano/lib/pages/ThemeSettingsPage.svelte";

  export let data;
</script>

<ThemeSettingsPage {data}/>
