<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import Layout from "$pano/routes/plugin-ui/Layout.svelte";

  export let data;
</script>

<Layout {data}><slot /></Layout>
