<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import Page from "$pano/routes/plugin-ui/Page.svelte";

  export let data;
</script>

<Page {data} />
