<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import SupportPage from "$pano/lib/pages/SupportPage.svelte";

  export let data;
</script>

<SupportPage {data}/>
