import {
  API_URL,
  COOKIE_PREFIX,
  CSRF_TOKEN_COOKIE_NAME,
  JWT_COOKIE_NAME,
  updateApiUrl,
  updatePanoWebsiteUrl
} from "$lib/variables.js";
import { getCredentialsServerSide } from "$lib/services/auth.js";
import { internalLibsHash } from "$lib/internalLibs.js";
import {
  isPremiumBuild,
  verifyLicenseFromEnv,
  assertStillLicensed,
  LicenseError,
} from "$lib/server/license-runtime.js";

// One-shot license verification at boot. For premium builds the Pano host sets
// PANO_LICENSE_JWT before spawning bun; the runtime helper verifies the RS256 signature
// + claim checks against the panomc.com public key embedded at build time. Free builds
// (this is one — manifest.premium === false) no-op everything. Vanilla ships with the
// hook in place so a developer cloning vanilla as a template to make a premium theme
// only needs to flip `"premium": true` in manifest.json and the rest is automatic.
let bootLicenseError = null;
if (isPremiumBuild()) {
  try {
    verifyLicenseFromEnv();
    console.log("[pano-license] startup verification passed");
  } catch (e) {
    bootLicenseError = e instanceof LicenseError ? e : new LicenseError("unknown", String(e?.message ?? e));
    console.error("[pano-license] startup verification FAILED:", bootLicenseError.message);
  }
}

function stripModulePreload(linkHeader) {
  const parts = linkHeader
    .split(",")
    .map((p) => p.trim())
    .filter(Boolean);

  const kept = parts.filter((p) => !/;\s*rel="?modulepreload"?/i.test(p));

  return kept.length ? kept.join(", ") : null;
}

function getCookieWithHttpFallback(cookies, baseName) {
  return cookies.get(baseName) ?? cookies.get(`${baseName}_http`);
}

const isDev = process.env.NODE_ENV === "development";

/** In production, skip logging common client/bot noise (wrong method, stray POST to non-action routes). */
function shouldSuppressServerErrorLog(error) {
  if (process.env.NODE_ENV !== "production") return false;
  if (error?.status === 405) return true;
  const msg = String(error?.message ?? "");
  if (msg.includes("No form actions exist")) return true;
  return false;
}
// Content-hashed lib namespace. The hash is generated by scripts/bundle-internal-libs.js
// and embedded into the importmap, so the URL uniquely identifies the content. A `?v=`
// query string would not work — the server ignores it and would serve the current file for
// any v, which causes ABI mismatches when stale clients fetch new svelte/sdk bundles.
const libBase = `/lib/${internalLibsHash}`;
const importMap = `
  <script type="importmap" crossorigin="anonymous">
  {
    "imports": {
      "svelte": "${isDev ? "/@id/svelte" : `${libBase}/svelte/index.js`}",
      "svelte/animate": "${isDev ? "/@id/svelte/animate" : `${libBase}/svelte/animate.js`}",
      "svelte/easing": "${isDev ? "/@id/svelte/easing" : `${libBase}/svelte/easing.js`}",
      "svelte/motion": "${isDev ? "/@id/svelte/motion" : `${libBase}/svelte/motion.js`}",
      "svelte/store": "${isDev ? "/@id/svelte/store" : `${libBase}/svelte/store.js`}",
      "svelte/transition": "${isDev ? "/@id/svelte/transition" : `${libBase}/svelte/transition.js`}",
      "svelte/internal": "${isDev ? "/@id/svelte/internal" : `${libBase}/svelte/internal.js`}",
      "svelte/internal/client": "${isDev ? "/@id/svelte/internal/client" : `${libBase}/svelte/internal-client.js`}",
      "svelte/internal/disclose-version": "${isDev ? "/@id/svelte/internal/disclose-version" : `${libBase}/svelte/internal-disclose-version.js`}",
      "svelte/internal/flags/legacy": "${isDev ? "/@id/svelte/internal/flags/legacy" : `${libBase}/svelte/internal-flags-legacy.js`}",
      "svelte/internal/flags/async": "${isDev ? "/@id/svelte/internal/flags/async" : `${libBase}/svelte/internal-flags-async.js`}",
      "svelte/internal/flags/tracing": "${isDev ? "/@id/svelte/internal/flags/tracing" : `${libBase}/svelte/internal-flags-tracing.js`}",
      "svelte/internal/server": "${isDev ? "/@id/svelte/internal/server" : `${libBase}/svelte/internal-server.js`}",
      "svelte/legacy": "${isDev ? "/@id/svelte/legacy" : `${libBase}/svelte/legacy.js`}",
      "svelte/events": "${isDev ? "/@id/svelte/events" : `${libBase}/svelte/events.js`}",
      "svelte-i18n": "${isDev ? "/@id/svelte-i18n" : `${libBase}/svelte/i18n.js`}",
      "@panomc/sdk": "${libBase}/sdk/index.js",
      "@panomc/sdk/components/theme": "${libBase}/sdk/components-theme.js",
      "@panomc/sdk/components/panel": "${libBase}/sdk/components-panel.js",
      "@panomc/sdk/toasts": "${libBase}/sdk/toasts.js",
      "@panomc/sdk/utils/api": "${libBase}/sdk/utils-api.js",
      "@panomc/sdk/utils/auth": "${libBase}/sdk/utils-auth.js",
      "@panomc/sdk/utils/tooltip": "${libBase}/sdk/utils-tooltip.js",
      "@panomc/sdk/utils/language": "${libBase}/sdk/utils-language.js",
      "@panomc/sdk/utils/component": "${libBase}/sdk/utils-component.js",
      "@panomc/sdk/utils/text": "${libBase}/sdk/utils-text.js",
      "@panomc/sdk/variables": "${libBase}/sdk/variables.js",
      "@panomc/sdk/svelte": "${libBase}/sdk/svelte.js",
      "@panomc/sdk/internal": "${libBase}/sdk/internal.js"
    }
  }
  </script>
  <script defer src="${libBase}/bootstrap/bootstrap.bundle.min.js"></script>`;
const IMPORT_MAP_PLACEHOLDER = "%pano_lib_import%";
const IMPORT_MAP_PLACEHOLDER_LEN = IMPORT_MAP_PLACEHOLDER.length;

function renderLicenseBlocked(reason, message) {
  // Minimal HTML page; deliberately self-contained so the broken theme can't accidentally
  // serve its own (now-unlicensed) UI. The Pano host's renewal sweep will fall back to the
  // bundled vanilla theme on next sweep, but until then we surface the cause.
  const body =
    "<!doctype html><html lang=\"en\"><head>" +
    "<meta charset=\"utf-8\"><title>License required</title>" +
    "<meta name=\"robots\" content=\"noindex\">" +
    "<style>html,body{height:100%;margin:0;font-family:system-ui,sans-serif;color:#222;background:#f7f7f9}" +
    "main{display:flex;align-items:center;justify-content:center;height:100%;padding:2rem;text-align:center}" +
    "section{max-width:540px}h1{margin:.2em 0 .6em}code{background:#eee;padding:.1em .3em;border-radius:.2em}" +
    ".reason{color:#a00;font-weight:600}</style></head><body><main><section>" +
    "<h1>This premium theme is not licensed on this server.</h1>" +
    "<p>The Pano host did not provide a valid license token.</p>" +
    `<p>Reason: <span class="reason">${escapeHtml(reason)}</span>${message ? ` — ${escapeHtml(message)}` : ""}</p>` +
    "<p>Open the Pano panel and reconnect your panomc.com account, then re-activate this theme.</p>" +
    "</section></main></body></html>";
  return new Response(body, {
    status: 503,
    headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" },
  });
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    "\"": "&quot;",
    "'": "&#39;",
  }[c]));
}

/** @type {import('@sveltejs/kit').Handle} */
export async function handle({
  event,
  event: {
    cookies,
    url: { pathname },
  },
  resolve,
}) {
  // License gate: every request to a premium theme has to pass the cached check. Free
  // builds short-circuit because isPremiumBuild() is false.
  if (isPremiumBuild()) {
    if (bootLicenseError) {
      return renderLicenseBlocked(bootLicenseError.reason ?? "unknown", bootLicenseError.message);
    }
    try {
      assertStillLicensed();
    } catch (e) {
      const reason = e instanceof LicenseError ? e.reason : "unknown";
      return renderLicenseBlocked(reason, e?.message);
    }
  }

  const locals = {};

  // noinspection JSUnresolvedReference
  const apiUrlEnv = process.env.API_URL;

  // noinspection JSUnresolvedReference
  const panoWebsiteUrlEnv = process.env.PANO_WEBSITE_URL;

  if (apiUrlEnv) {
    updateApiUrl(apiUrlEnv);
    locals.apiUrlEnv = apiUrlEnv;
  }

  if (panoWebsiteUrlEnv) {
    updatePanoWebsiteUrl(panoWebsiteUrlEnv);
    locals.panoWebsiteUrlEnv = panoWebsiteUrlEnv;
  }

  const jwt = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + JWT_COOKIE_NAME);
  const csrfToken = getCookieWithHttpFallback(cookies, COOKIE_PREFIX + CSRF_TOKEN_COOKIE_NAME);

  locals.user =
    jwt && csrfToken &&
    !pathname.startsWith("/api/") &&
    !pathname.startsWith("/auth/") &&
    (await getCredentialsServerSide(jwt));

  locals.csrfToken = csrfToken;

  event.locals = locals;

  const response = await resolve(event, {
    transformPageChunk: ({ html }) => {
      const index = html.indexOf(IMPORT_MAP_PLACEHOLDER);
      if (index === -1) return html;
      return html.substring(0, index) + importMap + html.substring(index + IMPORT_MAP_PLACEHOLDER_LEN);
    },
  });

  const ct = response.headers.get("content-type") || "";
  if (ct.includes("text/html")) {
    const link = response.headers.get("link");
    if (link) {
      const filtered = stripModulePreload(link);
      if (filtered) response.headers.set("link", filtered);
      else response.headers.delete("link");
    }
  }

  return response;
}

/** @type {import('@sveltejs/kit').HandleServerError} */
export function handleError({ error, event }) {
  if (!shouldSuppressServerErrorLog(error)) {
    console.log("!!! [GLOBAL ERROR EVENT]:", event.url.href);
    console.error("!!! [GLOBAL ERROR CONTENT]:", error);
  }
  return {
    message: 'Internal Error',
    code: error?.code
  };
}

/** @type {import("@sveltejs/kit").HandleFetch} */
export async function handleFetch({ event, request, fetch }) {
  // Rewrite relative /api/ requests to the backend URL during SSR.
  // Load functions now use relative paths for consistent SSR↔CSR fetch dedup.
  if (request.url.startsWith(event.url.origin + "/api/")) {
    const apiPath = new URL(request.url).pathname + new URL(request.url).search;
    const backendUrl = API_URL.replace(/\/api\/?$/, "") + apiPath;
    request = new Request(backendUrl, request);
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  } else if (request.url.startsWith(API_URL)) {
    request.headers.set("cookie", event.request.headers.get("cookie") || "");
    request.headers.set("Origin", API_URL);
  }

  return fetch(request);
}