// AUTO-GENERATED by theme-core sync — do not edit.
// To take ownership of this file, add an eject comment (see theme-core docs).
import themeConfig from "../theme.config.js";
import { createReroute, setRouteConfig } from "$pano/registry/routes.js";

// Module side effect, like the root layout: route() knows the renames on the server and the client.
setRouteConfig(themeConfig);

export const reroute = createReroute(themeConfig);
