<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import NotificationsPage from "$pano/lib/pages/NotificationsPage.svelte";

  export let data;
</script>

<NotificationsPage {data}/>
