<!-- AUTO-GENERATED by theme-core sync — do not edit. To take ownership, add an eject comment (see theme-core docs). -->
<script>
  import SettingsPage from "$pano/lib/pages/profile/SettingsPage.svelte";

  export let data;
</script>

<SettingsPage {data}/>
